name: Production deployment

on: 
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: alius-probatio-rg
  AZURE_APP_PLAN: actions-ttt-deployment
  AZURE_LOCATION: '"North Europe"'
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: safaie-ttt-app
  #################################################
  
